services:
  init:
    build:
      context: ./init
      dockerfile: Containerfile
    container_name: registry_init
    env_file:
      - ./.env
    volumes:
      - ${DATA_ROOT}/auth:/auth
      - ${DATA_ROOT}/certs:/certs

  nginx:
    build:
      context: ./nginx
      dockerfile: Containerfile
    container_name: registry_nginx
    restart: always
    env_file:
      - ./.env
    ports:
      - "80:80"
      - "${REGISTRY_PORT:-443}:443"
    volumes:
      # Mount the nginx config template
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template
      # Mount the htpasswd file
      - ${DATA_ROOT}/auth:/etc/nginx/auth
      # Mount SSL certs
      - ${DATA_ROOT}/certs:/etc/nginx/certs:ro
    depends_on:
      registry:
        condition: service_started
      init:
        condition: service_completed_successfully

  registry:
    image: registry:2
    container_name: registry_service
    restart: always
    environment:
      # Configure registry to use htpasswd
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /etc/nginx/auth/htpasswd
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      # Mount registry data (Bind mount from host path)
      - ${DATA_ROOT}/images:/var/lib/registry
      # Mount htpasswd file (read-only for registry)
      - ${DATA_ROOT}/auth:/etc/nginx/auth:ro
    depends_on:
      init:
        condition: service_completed_successfully
