FROM docker.io/library/nginx:alpine

# Install gettext for envsubst
RUN apk add --no-cache gettext certbot certbot-nginx

COPY nginx.conf /etc/nginx/nginx.conf.template

# Use an entrypoint script to substitute environment variables in the config
CMD /bin/sh -c "envsubst '\$REGISTRY_DOMAIN' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
