FROM docker.io/library/nginx:alpine

# Install certbot-nginx for the 'exec' command capability, 
# although certbot logic is mainly driven from outside or via exec.
# We keep it to ensure 'certbot' command is available inside the container.
RUN apk add --no-cache certbot certbot-nginx

# Overwrite default nginx config
COPY nginx.conf /etc/nginx/nginx.conf

# We do NOT run envsubst here anymore. 
# The dynamic config will be mounted into /etc/nginx/conf.d/
CMD ["nginx", "-g", "daemon off;"]